version: '3.4'

services:
  server:
    image: goreminder
    container_name: 'goreminder'
    build: ./Dockerfile.local
    volumes:
      - ./.build/volumes/logs:/logs
    env_file:
      - .env
    ports:
      - 3500:3500
